[package]
name = "createradixdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
radixdb = "0.2.5"
anyhow = "1.0.80"
rand = "0.8.5"
